fragment BlogsParts on Blogs {
  __typename
  title
  description
  pubDate
  category
  author
  heroImage
  heroImageAlt
  body
}

fragment CategoriesParts on Categories {
  __typename
  label
  slug
  heroImage
}
