name: CI & Deploy

on:
  push:
    branches:
      - main
      - production
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  prepare:
    name: Prepare assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Ensure favicon.svg present
        run: |
          # Caminhos possíveis — ajuste conforme sua estrutura
          if [ -f public/favicon.svg ]; then
            echo "favicon.svg already in public/"
          elif [ -f src/assets/favicon.svg ]; then
            echo "Copying favicon from src/assets"
            mkdir -p public
            cp src/assets/favicon.svg public/favicon.svg
          else
            echo "Error: favicon.svg not found in known paths."
            exit 1
          fi

  build:
    name: Build site
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workflow: [ astro, deploy ]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build (Astro + your scripts)
        run: npm run build

      # Use a conditional to trigger the correct deploy depending on branch
      - name: Deploy via Astro / GitHub Pages
        if: github.ref == 'refs/heads/production'
        uses: withastro/action@v2

      - name: Deploy to Hostinger (FTP)
        if: github.ref == 'refs/heads/main'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USER }}
          password: ${{ secrets.HOSTINGER_PASS }}
          local-dir: .vercel/output/static/
          server-dir: ./
          dangerous-clean-slate: false
          exclude: |
            **/.well-known/**
            **/mail/**

  deploy-pages:
    name: Deploy to GitHub Pages
    needs: build
    if: github.ref == 'refs/heads/production'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
