name: Deploy to Hostinger

on:
  push:
    branches: [ main ]
    paths:
      # código e conteúdo que exigem rebuild/deploy
      - 'src/**'
      - 'src/content/**'   # <- posts/MD do Tina entram aqui
      - 'public/**'
      - 'tina/**'
      - 'astro.config.mjs'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/deploy.yml'  # mudar o workflow também dispara
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  workflow_dispatch: {}

# evita filas/duplicados quando vários commits caem em sequência
concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    # permite pular o deploy com "[skip deploy]" na mensagem do commit
    if: ${{ !contains(github.event.head_commit.message, '[skip deploy]') }}
    runs-on: ubuntu-latest

    env:
      TINA_CLIENT_ID: ${{ secrets.TINA_CLIENT_ID }}
      TINA_TOKEN: ${{ secrets.TINA_TOKEN }}
      TINA_BRANCH: main
      NODE_OPTIONS: --max-old-space-size=4096

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci

      # seu script "build" já executa: build:cms + astro check + astro build
      - name: Build (Astro + Tina)
        run: npm run build

      # Sanity check: garante que o painel /admin foi gerado para o build estático
      - name: Check admin is in output
        run: |
          ls -la .vercel/output/static/admin || (echo "Admin não encontrado. Verifique 'public/admin' e o build." && exit 1)

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USER }}
          password: ${{ secrets.HOSTINGER_PASS }}
          local-dir: .vercel/output/static/
          server-dir: ./
          dangerous-clean-slate: false
          exclude: |
            **/.well-known/**
            **/mail/**
